#!/bin/bash
echo REACT_APP_ABIS_URL=$REACT_APP_ABIS_URL > .env
echo REACT_APP_GED_URL=$REACT_APP_GED_URL >> .env
echo REACT_APP_USERNAME=$REACT_APP_USERNAME >> .env
echo REACT_APP_PASSWORD=$REACT_APP_PASSWORD >> .env
echo REACT_APP_ABIS_VERIFICATION_URL=$REACT_APP_ABIS_VERIFICATION_URL >> .env
echo REACT_APP_IDLE_LOGOUT_TIME=$REACT_APP_IDLE_LOGOUT_TIME >> .env
